version: "1.0"
services:
  db:
    container_name: "randomizer"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=randomiser
    ports:
      - "5432:5432"
    networks:
      - custom
  db_test:
    container_name: "randomiser_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=randomiser_test
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge