"""dd

Revision ID: 7cf1a7662c68
Revises: 4112423b1aa6
Create Date: 2025-03-09 17:01:33.402249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf1a7662c68'
down_revision: Union[str, None] = '4112423b1aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_string',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_string')
    # ### end Alembic commands ###
